** Everything

Everything[fn:14] is a wonderful fast file and folder search engine, it provide
a command line tool to get search result from Everything to command line output:
=es.exe= [fn:15].

Reminded that Everything should be running in background to do the real search
task for =es.exe=.

#+BEGIN_SRC emacs-lisp
  (use-package everything
    :defer t
    :ensure t
    :init
    (setq everything-cmd (concat kimim/path-kimikit "bin/es.exe")))
#+END_SRC

** Simplenote2

#+BEGIN_SRC emacs-lisp
  (use-package markdown-mode
    :defer t
    :ensure t
    )

  (use-package simplenote2
    :defer t
    :ensure t
    :bind
    (
     ("C-x p" . simplenote2-list)
     ;; when in Chinese environment, / is a dot, confusing
     ("C-;" . simplenote2-list-filter-notes)
     ("C-." . simplenote2--create-note-locally))
    :config
    (require 'simplenote2)
    (require 'markdown-mode)
    ;;(require 'visual-fill-column)
    (setq simplenote2-notes-mode 'markdown-mode)
    ;;(add-hook 'simplenote2-note-mode-hook 'visual-fill-column-mode)
    (simplenote2-setup)
    )
#+END_SRC

New orgmode link type for simplenote2. The reason for creating a new kind of
link type is that the newly added note is located under folder "new", while the
synchronized notes are in "notes". We should ensure that all the link points to
note in "notes" folder.

#+BEGIN_SRC emacs-lisp :tangle no
  (use-package org
    :defer t
    :config
    (org-add-link-type "simplenote2" 'org-simplenote2-open)

    (defun org-simplenote2-open (path)
      (find-file (concat simplenote2-directory "notes/" path)))

    (defun simplenotes-linkto-note ()
      "extract orgmode link string to this note"
      (interactive)
      (unless (buffer-file-name)
        (error "No file for buffer %s" (buffer-name)))
      (beginning-of-buffer)
      (let (title msg)
        ;;fetch first line string as title
        (setq title (buffer-substring-no-properties
                     (line-beginning-position) (line-end-position)))
        ;;package orgmode line with buffer name and title
        (setq msg (format "[[simplenote2:%s][%s]]"
                          (file-name-nondirectory (buffer-file-name))
                          title))
        (kill-new msg)
        (message msg))))
#+END_SRC


** BBDB for contact management

#+BEGIN_SRC emacs-lisp
  (use-package bbdb
    :defer t
    :bind
    :config
    (setq bbdb-file (concat kimim/path-sync "kimikit/emacs.d/bbdb"))
    ;; https://www.emacswiki.org/emacs/BbdbMailingLists
    ;;(add-hook 'message-setup-hook 'bbdb-mail-aliases)
    )
#+END_SRC
** GNUS setting

#+begin_src emacs-lisp
  ;; gnus settings
  (use-package gnus
    :ensure nil
    :defer t
    :bind
    (("C-x m m" . kimim/mail-new-empty)
     ("C-x m n" . kimim/mail-new)
     ("C-x m y" . kimim/mail-attach-files)
     :map gnus-summary-mode-map
     ("g" . gnus-summary-insert-new-articles)
     ("f" . gnus-summary-forward-with-original)
     ("R" . gnus-summary-very-wide-reply-with-original)
     ("<delete>" . gnus-summary-delete-article)
     ("<insert>" . mail-archive-kimim))
    :config
    (message "......gnus[0]")
    (use-package ebdb)
    (use-package gnus-dired :ensure nil)
    (setq gnus-visible-headers
          "^Subject:\\|^From:\\|^To:\\|^[BGF]?CC:\\|^Date:")
    (setq gnus-sorted-header-list
          '("^Subject:" "^From:""^To:" "^[BGF]?CC:" "^Date:"))
    (setq compose-mail-user-agent-warnings nil) ;; remove warning
    (setq message-directory "~/Gnus/Mail/")
    (setq gnus-directory "~/Gnus/News/")
    (setq nnfolder-directory "~/Gnus/Mail/Archive")
    ;; unfortunately, following variable not support CN strings
    (setq gnus-permanently-visible-groups "\\(Inbox\\|INBOX\\|已发送邮件\\)")
    (setq mail-self-blind t)
    (setq gnus-alias-override-user-mail-address t)
    (setq mail-signature-file (concat kimim/path-sync "kimikit/emacs.d/signature.txt"))
    (setq gnus-asynchronous t)
    (setq gnus-use-article-prefetch 1000)
    (setq gnus-fetch-old-headers 'some)
    ;; fetch only 50 latest articles to speed up downloading
    (setq gnus-large-newsgroup 50)
    (setq message-forward-as-mime t)
    (setq message-forward-before-signature t) ;; put signature before the fwd msg
    (setq message-forward-included-headers "^Date\\|^From\\|^To\\|^Subject:")
    (setq message-make-forward-subject-function 'message-forward-subject-fwd)
    (setq gnus-user-date-format-alist
          '(((gnus-seconds-today) . "Today %H:%M")
            ((+ 86400 (gnus-seconds-today)) . "Yest. %H:%M")
            (604800 . "%a %H:%M")               ; That's one week
            ((gnus-seconds-month) . "%a %H:%M")
            ((gnus-seconds-year) . "%b %d")
            (t . "%b %d %Y")))
    (setq gnus-summary-line-format
          ":%U%R | %d%13&user-date; %-13,13f (%5k) | %B %s %-120= \n")
    (setq gnus-article-sort-functions '((not gnus-article-sort-by-date)))
    (setq gnus-thread-sort-functions '((not gnus-thread-sort-by-date)))
    (setq gnus-thread-ignore-subject t)
    (setq gnus-agent t)
    (setq gnus-agent-expire-days 90)
    ; prompt for how many articles only for larger than 1000 articles
    (setq gnus-large-newsgroup 100)
    (setq gnus-use-cache t)
    (setq gnus-fetch-old-headers 1) ; show previous messages in a thread
    (setq gnus-thread-indent-level 1)
    (setq gnus-show-threads t)
    (setq gnus-thread-hide-subtree nil)
    (add-hook 'gnus-summary-prepare-hook 'gnus-summary-hide-all-threads)
    ;;(use-package orgalist)
    ;;(add-hook 'message-mode-hook 'orgalist-mode)
    (add-hook 'message-mode-hook 'turn-off-auto-fill)
    (defun gnus-summary-forward-with-original (n &optional wide)
      "Start composing a reply mail to the current message.
  The original article will be yanked."
      (interactive "P")
      (gnus-summary-reply (gnus-summary-work-articles n) wide)
      (mail-to)
      (message-beginning-of-line)
      (kill-line)
      (mail-subject)
      (message-beginning-of-line)
      (delete-char 2)
      (narrow-to-region (line-beginning-position) (line-end-position))
      (goto-char (point-min))
      (while (search-forward "Fw: " nil t)
        (replace-match ""))
      (while (search-forward "转发： " nil t)
        (replace-match ""))
      (widen)
      (message-beginning-of-line)
      (insert "FW")
      (mail-to))

    (define-key gnus-summary-mode-map
      [remap gnus-summary-followup-with-original]
      'gnus-summary-forward-with-original)

    (define-key gnus-summary-mode-map
      [remap gnus-summary-reply]
      'gnus-summary-reply-with-original)

    (define-key gnus-summary-mode-map
      [remap gnus-summary-wide-reply]
      'gnus-summary-very-wide-reply-with-original)

    (add-hook 'gnus-message-setup-hook 'kimim/mail-setup))
#+end_src
** C

#+begin_src emacs-lisp
  ;; Define the modes/packages you need
  (use-package company-irony)

  (use-package irony
    :diminish irony-mode
    :config
    (setq w32-pipe-read-delay 0)
    (use-package company-irony)
    (add-hook 'irony-mode-hook 'company-irony-setup-begin-commands)
    (add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)

    ;; replace the `completion-at-point' and `complete-symbol' bindings in
    ;; irony-mode's buffers by irony-mode's function
    (defun my-irony-mode-hook ()
      (define-key irony-mode-map [remap completion-at-point]
        'irony-completion-at-point-async)
      (define-key irony-mode-map [remap complete-symbol]
        'irony-completion-at-point-async))
    (add-hook 'irony-mode-hook 'my-irony-mode-hook))

  (use-package company-c-headers)

  (use-package flycheck
    :config
    ;; set up flycheck
    (add-hook 'flycheck-mode-hook #'flycheck-irony-setup))

  (use-package cc-mode
    :ensure nil
    :config
    (add-to-list 'auto-mode-alist '("\\.C\\w*\\'" . c-mode))
    (use-package company)
    (use-package company-irony)
    (add-to-list 'company-backends 'company-irony)
    (use-package company-c-headers)
    (add-to-list 'company-c-headers-path-system "/usr/include")
    (require 'irony)
    (add-hook 'c-mode-hook 'irony-mode)
    (add-hook 'c++-mode-hook 'irony-mode)
    (add-hook 'objc-mode-hook 'irony-mode)
    (require 'flycheck)
    (add-hook 'c-mode-hook 'flycheck-mode)
    (add-hook 'c++-mode-hook 'flycheck-mode)
    (require 'ggtags)
    (add-hook 'c-mode-hook 'ggtags-mode)
    (add-hook 'c++-mode-hook 'ggtags-mode)

    (add-hook 'c-mode-common-hook
              (lambda ()
                ;; show column width indicator
                ;;(fci-mode 0)
                ;;(syntax-subword-mode 1)
                ;;(hs-minor-mode 0)
                ;;(c-set-style "gnu")
                (c-toggle-auto-newline 0)
                (c-toggle-auto-hungry-state 0)
                (c-toggle-syntactic-indentation 1)
                ;;(highlight-indentation-mode 1)
                (which-function-mode 1)
                (local-set-key "\C-co" 'ff-find-other-file)
                ;;(my-c-mode-common-hook-if0)
                (setq c-basic-offset 4))))
#+end_src

*** irony installation

=irony-mode= is developed by Sarcasm [fn:13]. It is an Emacs minor-mode that
aims at improving the editing experience for the C, C++ and Objective-C
languages. It works by using a combination of an Emacs package and a C++ program
(=irony-server=) that uses libclang. When correctly configured, it can provide
wonderful auto completion for functions and variables. The function prototypes
with parameters can be triggered as a yasnippet automatically.

It is quite easy to install =irony-server= under macOS, just invoke the command
"M-x irony-install-server", and Emacs will compile and install it to
=~/.emacs.d/irony/bin/irony-server=, by invoking the make commands:

#+begin_src shell
  cmake -DCMAKE_INSTALL_PREFIX\=/Users/kimim/.emacs.d/irony/
  /Users/kimim/.emacs.d/elpa/irony-20160925.1030/server && cmake --build
  . --use-stderr --config Release --target install
#+end_src

For Cygwin/Windows, first we should install =libclang= 3.8.1-1 and
=libclang-devel= 3.8.1-1 and =cmake= with =setup.exe=.

Then compile =irony-server= with =cmake= and =make=:

#+begin_src shell
~/.emacs.d/elpa/irony-20160925.1030/server/build
$ cmake -DCMAKE_INSTALL_PREFIX=~/.emacs.d/irony/ -G "Unix Makefiles" ..

~/.emacs.d/elpa/irony-20160925.1030/server/build
$ make install
Scanning dependencies of target irony-server
[ 14%] Building CXX object src/CMakeFiles/irony-server.dir/support/CommandLineParser.cpp.o
[ 28%] Building CXX object src/CMakeFiles/irony-server.dir/support/TemporaryFile.cpp.o
[ 42%] Building CXX object src/CMakeFiles/irony-server.dir/Command.cpp.o
[ 57%] Building CXX object src/CMakeFiles/irony-server.dir/Irony.cpp.o
[ 71%] Building CXX object src/CMakeFiles/irony-server.dir/TUManager.cpp.o
[ 85%] Building CXX object src/CMakeFiles/irony-server.dir/main.cpp.o
[100%] Linking CXX executable ../bin/irony-server.exe
[100%] Built target irony-server
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /home/kimim/.emacs.d/irony/bin/irony-server.exe
#+end_src
